export { default as Navbar} from './navbar'
export { default as Home} from './home'
export { default as Statistics} from './statistics'
export { default as Contract} from './contract'
export { default as Biling } from './biling'
export { default as Business} from './business'
export { default as FeatureCard} from './feature-card'
export { default as CTA} from './cta'
export { default as Testimonials } from './testimonials'
export { default as Clients} from './clients'
export { default as Footer} from './footer'